[tools]
java = "17"
maven = "3.8.8"

[tasks.spotless]
run = "./mvnw spotless:check -B"
[tasks.run]
run = "./mvnw quarkus:dev"
[tasks.build]
run = "./mvnw package"
[tasks.test]
run = "./mvnw test"
[tasks.lint]
run = "./mvnw spotless:apply -B"
