quarkus:
  devservices:
    log:
      sql: true
    enabled: false  # Add this line to use your own DB on port 5433
  hibernate-orm:
    database:
      generation: update
  datasource:
    db-kind: postgresql
    username: admin
    password: admin
    jdbc:
      url: jdbc:postgresql://localhost:5433/admin
      max-size: 16

  cache:
   caffeine:
    "country-cache":
     maximum-size: 1000
     expire-after-write: 24H
     expire-after-access: 7D
     metrics-enabled: true